//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public int UserId { get; set; }
        public int Roles_Id { get; set; }
        public int leaveManagemetId { get; set; }
        public int PerformanceId { get; set; }
        public int Department_Id { get; set; }
        public int Salary_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public int id_number { get; set; }
        public string address { get; set; }
        public int phone { get; set; }
        public string qualification { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual LeaveManagement LeaveManagement { get; set; }
        public virtual Perfomance Perfomance { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
